In [1]:
import pandas as pd

# Create dataset
data = {
    "Student": ["A","B","C","D","E","F","G","H","I","J"],
    "Passed": ["Yes","No","Yes","Yes","No",
               "Yes","Yes","No","Yes","Yes"]
}

df = pd.DataFrame(data)

df

  Student Passed
0       A    Yes
1       B     No
2       C    Yes
3       D    Yes
4       E     No
5       F    Yes
6       G    Yes
7       H     No
8       I    Yes
9       J    Yes

In [4]:
# Total count
total = len(df)
total

10

In [8]:
passed = len(df[df['Passed']=='Yes'])
passed

7

In [9]:
prob_passed = passed/total
print("Probability of passed", prob_passed)

Probability of passed 0.7

In [11]:
failed = len(df[df['Passed']=='No'])
failed

3

In [12]:
prob_failed = failed/total
print("Probability of failed", prob_failed)

Probability of failed 0.3

In [13]:
import pandas as pd

# Dataset
data = {
    "Student": ["A","B","C","D","E","F"],
    "Gender": ["Boy","Boy","Boy","Girl","Girl","Girl"],
    "Passed": ["Yes","No","Yes","Yes","No","Yes"]
}

df = pd.DataFrame(data)

df

  Student Gender Passed
0       A    Boy    Yes
1       B    Boy     No
2       C    Boy    Yes
3       D   Girl    Yes
4       E   Girl     No
5       F   Girl    Yes

In [15]:
total = len(df)
total

6

## Probability of Boy and Passed

In [16]:
boys = len(df[df['Gender']=='Boy'])
boys

3

In [17]:
passed = len(df[df['Passed']=='Yes'])
passed

4

In [18]:
boy_passed = len(df[(df['Gender']=='Boy') & (df['Passed']=='Yes')])
boy_passed

2

In [19]:
prob_boy_passed = (boys + passed - boy_passed)/total
prob_boy_passed

0.8333333333333334

In [21]:
girl = len(df[df['Gender']=='Girl'])
girl

3

In [20]:
girl_passed = len(df[(df['Gender']=='Girl') & (df['Passed']=='Yes')])
girl_passed

2

In [22]:
prob_girl_passed = (girl + passed - girl_passed)/total
prob_girl_passed

0.8333333333333334

In [24]:
failed = len(df[df['Passed']=='No'])
failed

2

In [23]:
girl_failed = len(df[(df['Gender']=='Girl') & (df['Passed']=='No')])
girl_failed

1

In [25]:
prob_girl_failed = (girl + failed - girl_failed)/total
prob_girl_failed

0.6666666666666666

In [26]:
prob_girl_failed = len(df[(df['Gender' ] == 'Girl') & (df['Passed' ] == 'No' ) ])/total
prob_girl_failed

0.16666666666666666

In [28]:
prob_boy_passed = len(df[(df['Gender' ] == 'Boy') & (df['Passed' ] == 'Yes' ) ])/total
prob_boy_passed

0.3333333333333333

In [30]:
data = {
    "Day" : [1,2,3,4,5,6,7,8,9,10],
    "Weather" : ["Hot", "Hot", "Hot", "Cold", "Cold", "Hot", "Cold", "Hot", "Cold", "Hot"],
    "Bought_icecream" : ["Yes", "Yes", "No", "No", "No", "Yes", "Yes" ,"Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Day Weather Bought_icecream
0    1     Hot             Yes
1    2     Hot             Yes
2    3     Hot              No
3    4    Cold              No
4    5    Cold              No
5    6     Hot             Yes
6    7    Cold             Yes
7    8     Hot             Yes
8    9    Cold              No
9   10     Hot             Yes

## Hot and Bought icecream

In [31]:
total = len(df)
total

10

In [35]:
hot_n_bought_icecream = len(df[(df['Weather']=='Hot') & (df['Bought_icecream']=='Yes')])/total
hot_n_bought_icecream

0.5

## Cold and Bought icecream

In [36]:
cold_n_bought_icecream = len(df[(df['Weather']=='Cold') & (df['Bought_icecream']=='Yes')])/total
cold_n_bought_icecream

0.1

## Hot or Bought icecream

In [37]:
hot_or_bought_icecream = len(df[(df['Weather']=='Hot') | (df['Bought_icecream']=='Yes')])/total
hot_or_bought_icecream

0.7

## Cold or Bought icecream

In [38]:
cold_bought_or_icecream = len(df[(df['Weather']=='Cold') | (df['Bought_icecream']=='Yes')])/total
cold_bought_or_icecream

0.9