## Conditional probability & Bayes Theorem

In [1]:
import pandas as pd

data = {
    "Student": ["A","B","C","D","E","F","G","H","I","J"],
    "Cricket": ["Yes","Yes","Yes","No","No","Yes","No","Yes","No","Yes"],
    "Passed": ["Yes","Yes","No","Yes","No","Yes","No","Yes","Yes","No"]
}

df = pd.DataFrame(data)
df

  Student Cricket Passed
0       A     Yes    Yes
1       B     Yes    Yes
2       C     Yes     No
3       D      No    Yes
4       E      No     No
5       F     Yes    Yes
6       G      No     No
7       H     Yes    Yes
8       I      No    Yes
9       J     Yes     No

In [17]:
# Total
total = len(df)
total

10

In [4]:
# Play cricket
cricket = len(df[df['Cricket']=='Yes'])
cricket

6

In [5]:
# Passed
passed = len(df[df['Passed']=='Yes'])
passed

6

In [15]:
# Probability of plays cricket
prob_cricket = cricket/total
prob_cricket

0.6

In [16]:
# Prob. of passed
prob_passed = passed/total
prob_passed

0.6

In [10]:
# Prob. of plays cricket AND passed
prob_cric_pass = len(df[(df['Cricket' ] == 'Yes') & (df['Passed' ] == 'Yes' )])/len(df)
prob_cric_pass

0.4

In [11]:
# Prob. of plays cricket OR passed
prob_cric_or_pass = len(df[(df['Cricket' ] == 'Yes') | (df['Passed' ] == 'Yes' )])/len(df)
prob_cric_or_pass

0.8

### Probability of passed given he plays cricket

In [12]:
passed_given_cricket = prob_cric_pass/prob_cricket
passed_given_cricket

0.6666666666666667

### Bayes Theorem - probability of cricket given passed

In [13]:
cricket_given_passed = passed_given_cricket * prob_cricket / prob_passed
cricket_given_passed

0.6666666666666667

## Mean Absolute Deviation

In [18]:
data = {
    "Students" : ["A", "B", "C", "D", "E"],
    "Study_hours" : [2,4,6,8,10]
}

df = pd.DataFrame(data)
df

  Students  Study_hours
0        A            2
1        B            4
2        C            6
3        D            8
4        E           10

In [26]:
mean_value = df["Study_hours"].mean()
mean_value

np.float64(6.0)

In [27]:
df["Deviation" ] = df[ "Study_hours"] - mean_value
df

  Students  Study_hours  Deviation
0        A            2       -4.0
1        B            4       -2.0
2        C            6        0.0
3        D            8        2.0
4        E           10        4.0

In [28]:
df["Absolute_Deviation"] = abs(df["Deviation"])
df

  Students  Study_hours  Deviation  Absolute_Deviation
0        A            2       -4.0                 4.0
1        B            4       -2.0                 2.0
2        C            6        0.0                 0.0
3        D            8        2.0                 2.0
4        E           10        4.0                 4.0

In [29]:
mean_absolute_deviation = df["Absolute_Deviation"].mean()
mean_absolute_deviation

np.float64(2.4)

## Probability Distribution